"""create amenities tables

Revision ID: 0849ee2f4216
Revises: d6565f392e31
Create Date: 2026-08-03 18:12:22.590256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0849ee2f4216'
down_revision: Union[str, Sequence[str], None] = 'd6565f392e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_amenities_code'), 'amenities', ['code'], unique=True)
    op.create_table('bus_amenities',
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bus_id', 'amenity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bus_amenities')
    op.drop_index(op.f('ix_amenities_code'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
