"""create drivers table

Revision ID: 42ca193e04b2
Revises: 435abf979e4c
Create Date: 2026-08-04 17:26:48.013578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ca193e04b2'
down_revision: Union[str, Sequence[str], None] = '435abf979e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('assigned_bus_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_type', sa.String(length=50), nullable=True),
    sa.Column('license_issue_date', sa.Date(), nullable=True),
    sa.Column('license_expiry_date', sa.Date(), nullable=False),
    sa.Column('government_id_type', sa.String(length=50), nullable=True),
    sa.Column('government_id_number', sa.String(length=100), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'on_leave', 'suspended', 'terminated', name='driver_status_enum'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_bus_id'], ['buses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'license_number', name='uq_driver_operator_license')
    )
    op.create_index(op.f('ix_drivers_assigned_bus_id'), 'drivers', ['assigned_bus_id'], unique=False)
    op.create_index(op.f('ix_drivers_employee_code'), 'drivers', ['employee_code'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_license_expiry_date'), 'drivers', ['license_expiry_date'], unique=False)
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=False)
    op.create_index(op.f('ix_drivers_operator_id'), 'drivers', ['operator_id'], unique=False)
    op.create_index(op.f('ix_drivers_phone_number'), 'drivers', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_phone_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_operator_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_expiry_date'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_employee_code'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_assigned_bus_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
