"""create seat layout templates

Revision ID: 435abf979e4c
Revises: 0849ee2f4216
Create Date: 2026-08-03 18:53:09.193776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435abf979e4c'
down_revision: Union[str, Sequence[str], None] = '0849ee2f4216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_layout_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=75), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('number_of_decks', sa.Integer(), nullable=False),
    sa.Column('max_rows', sa.Integer(), nullable=False),
    sa.Column('max_columns', sa.Integer(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'name', name='uq_seat_layout_operator_name')
    )
    op.create_index(op.f('ix_seat_layout_templates_code'), 'seat_layout_templates', ['code'], unique=True)
    op.create_index(op.f('ix_seat_layout_templates_id'), 'seat_layout_templates', ['id'], unique=False)
    op.create_index(op.f('ix_seat_layout_templates_operator_id'), 'seat_layout_templates', ['operator_id'], unique=False)
    op.create_table('seat_layout_template_seats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layout_template_id', sa.Integer(), nullable=False),
    sa.Column('seat_label', sa.String(length=20), nullable=False),
    sa.Column('seat_type', sa.Enum('seater', 'semi_sleeper', 'sleeper', name='seat_type_enum'), nullable=False),
    sa.Column('deck', sa.Enum('single', 'lower', 'upper', name='seat_deck_enum'), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_number', sa.Integer(), nullable=False),
    sa.Column('orientation', sa.Enum('forward', 'rearward', 'sideways', name='seat_orientation_enum'), nullable=False),
    sa.Column('is_window', sa.Boolean(), nullable=False),
    sa.Column('is_aisle', sa.Boolean(), nullable=False),
    sa.Column('is_last_row', sa.Boolean(), nullable=False),
    sa.Column('is_ladies_reserved', sa.Boolean(), nullable=False),
    sa.Column('fare_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['layout_template_id'], ['seat_layout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layout_template_id', 'deck', 'row_number', 'column_number', name='uq_layout_template_seat_position'),
    sa.UniqueConstraint('layout_template_id', 'seat_label', name='uq_layout_template_seat_label')
    )
    op.create_index(op.f('ix_seat_layout_template_seats_id'), 'seat_layout_template_seats', ['id'], unique=False)
    op.create_index(op.f('ix_seat_layout_template_seats_layout_template_id'), 'seat_layout_template_seats', ['layout_template_id'], unique=False)
    op.add_column('buses', sa.Column('seat_layout_template_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_buses_seat_layout_template_id'), 'buses', ['seat_layout_template_id'], unique=False)
    op.create_foreign_key("fk_buses_seat_layout_template_id","buses","seat_layout_templates",["seat_layout_template_id"],["id"],ondelete="RESTRICT")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_buses_seat_layout_template_id","buses",type_="foreignkey")
    op.drop_index(op.f('ix_buses_seat_layout_template_id'), table_name='buses')
    op.drop_column('buses', 'seat_layout_template_id')
    op.drop_index(op.f('ix_seat_layout_template_seats_layout_template_id'), table_name='seat_layout_template_seats')
    op.drop_index(op.f('ix_seat_layout_template_seats_id'), table_name='seat_layout_template_seats')
    op.drop_table('seat_layout_template_seats')
    op.drop_index(op.f('ix_seat_layout_templates_operator_id'), table_name='seat_layout_templates')
    op.drop_index(op.f('ix_seat_layout_templates_id'), table_name='seat_layout_templates')
    op.drop_index(op.f('ix_seat_layout_templates_code'), table_name='seat_layout_templates')
    op.drop_table('seat_layout_templates')
    # ### end Alembic commands ###
