"""create buses table

Revision ID: 9339390c8d4e
Revises: b0f1a090d566
Create Date: 2026-07-25 14:40:23.364191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9339390c8d4e'
down_revision: Union[str, Sequence[str], None] = 'b0f1a090d566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('fleet_number', sa.String(length=50), nullable=True),
    sa.Column('bus_name', sa.String(length=150), nullable=False),
    sa.Column('bus_type', sa.Enum('seater', 'sleeper', 'semi_sleeper', 'seater_sleeper', name='bus_type_enum'), nullable=False),
    sa.Column('service_type', sa.Enum('ordinary', 'express', 'deluxe', 'luxury', 'premium', name='service_type_enum'), nullable=False),
    sa.Column('fuel_type', sa.Enum('diesel', 'petrol', 'cng', 'electric', 'hybrid', name='fuel_type_enum'), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_year', sa.Integer(), nullable=True),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('number_of_decks', sa.Integer(), nullable=False),
    sa.Column('has_air_conditioning', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'maintenance', 'retired', name='bus_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_fleet_number'), 'buses', ['fleet_number'], unique=False)
    op.create_index(op.f('ix_buses_id'), 'buses', ['id'], unique=False)
    op.create_index(op.f('ix_buses_operator_id'), 'buses', ['operator_id'], unique=False)
    op.create_index(op.f('ix_buses_registration_number'), 'buses', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buses_registration_number'), table_name='buses')
    op.drop_index(op.f('ix_buses_operator_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_fleet_number'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
