"""Add districts to location hierarchy

Revision ID: 98817887e0bb
Revises: 7125c5423db8
Create Date: 2026-07-25 12:28:05.338070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98817887e0bb'
down_revision: Union[str, Sequence[str], None] = '7125c5423db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.add_column('cities', sa.Column('district_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_cities_state_id'), table_name='cities')
    op.create_index(op.f('ix_cities_district_id'), 'cities', ['district_id'], unique=False)
    op.drop_constraint(op.f('cities_state_id_fkey'), 'cities', type_='foreignkey')
    op.create_foreign_key(None, 'cities', 'districts', ['district_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cities', 'state_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.create_foreign_key(op.f('cities_state_id_fkey'), 'cities', 'states', ['state_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cities_district_id'), table_name='cities')
    op.create_index(op.f('ix_cities_state_id'), 'cities', ['state_id'], unique=False)
    op.drop_column('cities', 'district_id')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
