"""Normalize operator management tables

Revision ID: b0f1a090d566
Revises: a51227707399
Create Date: 2026-07-25 13:06:09.992482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f1a090d566'
down_revision: Union[str, Sequence[str], None] = 'a51227707399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=False),
    sa.Column('routing_code', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'account_number', name='uq_operator_bank_account')
    )
    op.create_index(op.f('ix_operator_bank_accounts_operator_id'), 'operator_bank_accounts', ['operator_id'], unique=False)
    op.create_table('operator_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_contacts_operator_id'), 'operator_contacts', ['operator_id'], unique=False)
    op.add_column('operators', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('operators_email_key'), 'operators', type_='unique')
    op.drop_constraint(op.f('operators_phone_key'), 'operators', type_='unique')
    op.drop_index(op.f('ix_operators_owner_user_id'), table_name='operators')
    op.create_index(op.f('ix_operators_owner_user_id'), 'operators', ['owner_user_id'], unique=True)
    op.drop_column('operators', 'bank_account_number')
    op.drop_column('operators', 'bank_account_name')
    op.drop_column('operators', 'bank_name')
    op.drop_column('operators', 'email')
    op.drop_column('operators', 'phone')
    op.drop_column('operators', 'bank_routing_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('bank_routing_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('operators', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('operators', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('operators', sa.Column('bank_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('operators', sa.Column('bank_account_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('operators', sa.Column('bank_account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_operators_owner_user_id'), table_name='operators')
    op.create_index(op.f('ix_operators_owner_user_id'), 'operators', ['owner_user_id'], unique=False)
    op.create_unique_constraint(op.f('operators_phone_key'), 'operators', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('operators_email_key'), 'operators', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('operators', 'is_active')
    op.drop_index(op.f('ix_operator_contacts_operator_id'), table_name='operator_contacts')
    op.drop_table('operator_contacts')
    op.drop_index(op.f('ix_operator_bank_accounts_operator_id'), table_name='operator_bank_accounts')
    op.drop_table('operator_bank_accounts')
    # ### end Alembic commands ###
