"""create fleet master tables

Revision ID: d6565f392e31
Revises: dc9554498aa4
Create Date: 2026-08-03 17:35:44.429648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6565f392e31'
down_revision: Union[str, Sequence[str], None] = 'dc9554498aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_bus_classes_code'), 'bus_classes', ['code'], unique=True)
    op.create_table('bus_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_bus_configurations_code'), 'bus_configurations', ['code'], unique=True)
    op.create_table('bus_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_bus_types_code'), 'bus_types', ['code'], unique=True)
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_fuel_types_code'), 'fuel_types', ['code'], unique=True)
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_service_categories_code'), 'service_categories', ['code'], unique=True)
    op.add_column('buses', sa.Column('bus_type_id', sa.Integer(), nullable=True))
    op.add_column('buses', sa.Column('configuration_id', sa.Integer(), nullable=True))
    op.add_column('buses', sa.Column('fuel_type_id', sa.Integer(), nullable=True))
    op.add_column('buses', sa.Column('service_category_id', sa.Integer(), nullable=True))
    op.add_column('buses', sa.Column('bus_class_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_buses_bus_class_id'), 'buses', ['bus_class_id'], unique=False)
    op.create_index(op.f('ix_buses_bus_type_id'), 'buses', ['bus_type_id'], unique=False)
    op.create_index(op.f('ix_buses_configuration_id'), 'buses', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_buses_fuel_type_id'), 'buses', ['fuel_type_id'], unique=False)
    op.create_index(op.f('ix_buses_service_category_id'), 'buses', ['service_category_id'], unique=False)
    op.create_foreign_key(
    "fk_buses_bus_type_id",
    "buses",
    "bus_types",
    ["bus_type_id"],
    ["id"],
    ondelete="RESTRICT",
    )
    op.create_foreign_key(
    "fk_buses_service_category_id",
    "buses",
    "service_categories",
    ["service_category_id"],
    ["id"],
    ondelete="RESTRICT",
    )

    op.create_foreign_key(
        "fk_buses_fuel_type_id",
        "buses",
        "fuel_types",
        ["fuel_type_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    op.create_foreign_key(
        "fk_buses_configuration_id",
        "buses",
        "bus_configurations",
        ["configuration_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    op.create_foreign_key(
        "fk_buses_bus_class_id",
        "buses",
        "bus_classes",
        ["bus_class_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    "fk_buses_bus_class_id",
    "buses",
    type_="foreignkey",
    )

    op.drop_constraint(
        "fk_buses_configuration_id",
        "buses",
        type_="foreignkey",
    )

    op.drop_constraint(
        "fk_buses_fuel_type_id",
        "buses",
        type_="foreignkey",
    )

    op.drop_constraint(
        "fk_buses_service_category_id",
        "buses",
        type_="foreignkey",
    )

    op.drop_constraint(
        "fk_buses_bus_type_id",
        "buses",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_buses_service_category_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_fuel_type_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_configuration_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_bus_type_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_bus_class_id'), table_name='buses')
    op.drop_column('buses', 'bus_class_id')
    op.drop_column('buses', 'service_category_id')
    op.drop_column('buses', 'fuel_type_id')
    op.drop_column('buses', 'configuration_id')
    op.drop_column('buses', 'bus_type_id')
    op.drop_index(op.f('ix_service_categories_code'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index(op.f('ix_fuel_types_code'), table_name='fuel_types')
    op.drop_table('fuel_types')
    op.drop_index(op.f('ix_bus_types_code'), table_name='bus_types')
    op.drop_table('bus_types')
    op.drop_index(op.f('ix_bus_configurations_code'), table_name='bus_configurations')
    op.drop_table('bus_configurations')
    op.drop_index(op.f('ix_bus_classes_code'), table_name='bus_classes')
    op.drop_table('bus_classes')
    # ### end Alembic commands ###
